---
title: "Project Data Analysis"
author: "Congxing Zhu"
date: "11/12/2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,tidy=T,highlight = T,message = F, warning=F)
```

```{r}
library(readxl)
Data3 <- read_excel("/Users/congxingzhu/Desktop/Congxing Project/Data-Appendix 3.xls")
Data3 <- na.omit(Data3)
Data3 <- Data3[-1,]
row.names(Data3) <- c()
R <- rep(1:5,length=30)
TR <- rep(1:3,each=5,length=30)
D <- rep(c(7,14),each=15,length=30)
N <- rep(20,length=30)
W <- c(Data3$X__6)
Data4 <- data.frame(Day=D,Tre=TR,Rep=R,Num=N,WFT=W)
Data4$WFT <- as.numeric(as.character(Data4$WFT))
Data4$WFT[Data4$WFT>20] <- 20
Data6 <- Data4
Data6$Num[10] <- 22
Data6$WFT[10] <- 22
Data6$Num[21] <- 23
Data6$WFT[21] <- 23
Data6
```


```{r}
m1 <- glm(cbind(WFT,Num-WFT)~as.factor(Day)*as.factor(Tre)-1,family = binomial(link = "logit"),data = Data6)
summary(m1)
-2*logLik(m1)
BIC(m1)
summary(aov(m1))
t.test(WFT~Day,data = Data6)
```


```{r}
m2 <-lm(WFT~ as.factor(Day) * as.factor(Tre),data = Data6)
summary(m2)
```


```{r}
AIC(m1)
AIC(m2)
```

```{r}
shapiro.test(m1$residuals)
shapiro.test(m2$residuals)

```

```{r}
par(mfrow=c(2,2))
plot(Data4$Day,m1$residuals)
plot(Data4$Day,m2$residuals)
plot(Data4$Tre,m1$residuals)
plot(Data4$Tre,m2$residuals)
```


```{r}
cor(m1$residuals[-30],m1$residuals[-1])
cor(m2$residuals[-30],m2$residuals[-1])
```































