---
title: "Graph3"
author: "Congxing Zhu"
date: "11/13/2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,tidy = T,highlight = T,message = F,warning = F)
```

```{r}
library(readxl)
Data3 <- read_excel("/Users/congxingzhu/Desktop/Congxing Project/Data-Appendix 3.xls")
Data3 <- na.omit(Data3)
Data3 <- Data3[-1,]
row.names(Data3) <- c()
R <- rep(1:5,length=30)
TR <- rep(1:3,each=5,length=30)
D <- rep(c(7,14),each=15,length=30)
N <- rep(20,length=30)
W <- c(Data3$X__6)
Data4 <- data.frame(Day=D,Tre=TR,Rep=R,Num=N,WFT=W)
Data4$WFT <- as.numeric(as.character(Data4$WFT))
a <- aggregate(WFT~Tre+Day,FUN = mean,data = Data4)
par(mar=c(6,6,6,2)+0.1)
vv <- barplot(a$WFT,density=c(30,30,30),angle=c(60,90,135),col=c("black","purple","darkblue"),space = c(0.3,0.2,0.2,1.6,0.2,0.2),cex.axis = 1.2,cex.names = 1.2,ylim = c(0,25),ylab = "No. of WFT adults captured \n on YSCs",xlab = "WFT pupae inoculation day after the treatments were applied",xlim = c(-1,12),yaxt="n")
axis(1,at=c(-1:12),labels = c("","","","7","","","","","14","","","","",""),tck=0)
axis(2,pos = -1)
arrows(vv,c(14.54,16.92,15.44,15.91,18.17,15.44),vv,c(17.73,19.23,18.35,18.65,19.82,18.35),angle=90,code=3,length = 0.05)
legend("right",inset = 0.05,c("Fulcrum","Blank","Water"),pch =0,density=c(30,30,30),angle=c(60,90,135),col=c("black","purple","darkblue"),bty = "n")
```

